twig:
    default_path: "%kernel.project_dir%/src/Twig"
    paths:
        [
            "%kernel.project_dir%/templates",
            "%kernel.project_dir%/src/Twig",
            "%kernel.project_dir%/assets/images",
        ]
    globals:
        globals: '@Common\Adapter\Template\Globals\TemplateGlobalParamsService'

when@test:
    twig:
        strict_variables: true
