name: deploy

on:
  workflow_run:
    workflows:
      - "setup production"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          cd $GITHUB_WORKSPACE

      - name: Get application artifact
        uses: actions/download-artifact@v4
          with:
            name: app-production-artifact
            path: $GITHUB_WORKSPACE/

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: ""
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: "-rlgoDzvc --delete"
