name: Main on push

on:
  push:
    branches:
      - main

concurrency:
  group: main-on-push
  cancel-in-progress: true

jobs:
  # ---------------------------------------
  # Sets the application up for production
  # --------------------------------------
  setup-production:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Clone repository
        uses: actions/checkout@v4.1.7

      # Composer cache
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # NPM cache
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setting up project for deploy
        run: |
          cd $GITHUB_WORKSPACE
          make setup-deploy
        env:
          RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY }}
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}

      - name: Create application artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-production-artifact
          path: .
          overwrite: true

  # --------------------------------------
  # Deploy application on server
  # --------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: setup-production

    steps:
      - name: Get application artifact
        uses: actions/download-artifact@v4
        with:
          name: app-production-artifact
          path: .

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: ""
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: "-rlgoDzvc --delete"

      - name: Create entrypoint symbol
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            ln -sfn ${{ secrets.DEPLOY_PATH }}/public ${{ secrets.DEPLOY_PUBLIC_PATH }}
            ln -sfn ${{ secrets.DEPLOY_API_PUBLIC_PATH }} ${{ secrets.DEPLOY_PATH }}/public/api
            ln -sfn ${{ secrets.DEPLOY_API_PUBLIC_PATH }}/index.php ${{ secrets.DEPLOY_PUBLIC_PATH }}/index_api.php
            cp ${{ secrets.DEPLOY_PATH }}/../config/OrderList-client/Config.php ${{ secrets.DEPLOY_PATH }}/src/Common/Domain/Config/Config.php
            cp ${{ secrets.DEPLOY_PATH }}/../config/OrderList-client/HTTP_CLIENT_CONFIGURATION.php ${{ secrets.DEPLOY_PATH }}/src/Common/Adapter/HttpClientConfiguration/HTTP_CLIENT_CONFIGURATION.php
            chmod 644 ${{ secrets.DEPLOY_PATH }}/public/.htaccess
